name: Test, Build, and Update Coverage Badge

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the Docker images
        run: docker compose build

      - name: Run tests and generate coverage report
        run: |
          echo "GEMINI_API_KEY=fake_key_for_testing" > .env
          docker compose run --rm backend pytest --cov=. --cov-report=xml

      - name: Create Coverage Badge
        uses: sverre-stad/coverage-badge-action@v1
        with:
          path: backend/coverage.xml
          output: coverage.svg
          
      - name: Commit the badge
        uses: EndBug/add-and-commit@v9
        with:
          message: 'chore: Update coverage badge'
          add: 'coverage.svg'