name: Run Backend Tests & Update Coverage Badge

on:
  push:
    branches: [ main ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and run the Docker images
        run: docker compose -f docker-compose.yml -f docker-compose.ci.yml up -d

      - name: Wait for services to be ready
        run: sleep 10

      - name: Run tests and generate coverage report
        run: |
          echo "GEMINI_API_KEY=fake_key_for_testing" > .env
          docker compose -f docker-compose.yml -f docker-compose.ci.yml exec backend pytest --cov=. --cov-report=xml

      - name: Stop services
        if: always()
        run: docker compose -f docker-compose.yml -f docker-compose.ci.yml down

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: backend/coverage.xml

  update-badge:
    runs-on: ubuntu-latest
    needs: test-backend
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: backend

      - name: Generate Coverage Badge
        uses: tj-actions/coverage-badge-py@v2
        with:
          output: coverage.svg
          working-directory: backend

      - name: Commit the badge
        uses: EndBug/add-and-commit@v9
        with:
          message: 'chore: Update coverage badge'
          add: 'coverage.svg'